### ISSUE TITLE
BWWalkthrough fails due to 'NSUnknownKeyException'

### ISSUE THREAD

**Issue by grantv9** [ariok/BWWalkthrough#101]
I am trying to implement BWWalkthrough in my app that is based off a NavigationController. I followed the tutorial but every time I try to run my app, I get this error:

> Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<BWWalkthrough.BWWalkthroughPageViewController 0x7fd36e440390> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key iCloudLabel.'

The iCloudLabel is a label I have in one of my app's views (not the main view) and all of its IB outlets are connected correctly, so I am confused why that is throwing an error. I tried changing how the BWWalkthrough is shown (based off of how I already was showing a first-launch screen) by changing `self.present(walkthrough, animated: true) {
                ()->() in
                print("need walkthrough is false")
            }` to `self.navigationController?.pushViewController(walkthrough, animated: true)` but I still get the same error. How can I fix this?

**Comment by ariok** [comment]
Hello, there is something strange in your setup here. Can you check if in the storyboard identity inspector for that view controller you have added your custom view controller and not `BWWalkthroughPage` as custom class? it seems that you are trying to link the `iCloudLabel` outlet to a `BWWalkthroughPage` directly, you should instead create your custom subclass of `BWWalkthroughPage` and add you IBOutlet there.

**Comment by grantv9** [comment]
It looks like I forgot to change the pages to subclasses of `BWWalkthroughPage` - they were still `UIViewController`s. It works now, thanks for the help!
