### ISSUE TITLE
Z order affects staticTags

### ISSUE THREAD

**Issue by hernangonzalez** [ariok/BWWalkthrough#105]
Hello Guys,

Found that if a view with a static tag included to filter the animations, is found, the views that follow will not be animated. Even though they are not included in the staticTags property.

Note: thanks for the lib, saved me a lot of time ;).

Thanks,
H.

**Comment by ariok** [comment]
Can you provide more information? I'm trying to reproduce the issue without success.

**Comment by ariok** [comment]
yes :P do you mind to share the steps to reproduce the issue? 
From my understanding, let's say you are adding a view with tag 5 to the static views, then even views with tags 6, 7, whatever-gt-5 become static.
