### ISSUE TITLE
Swift 4 Xcode 9

### ISSUE THREAD

**Issue by cianiandreadev** [ariok/BWWalkthrough#107]
I'm trying to use your library on Xcode 9 (beta2) and Swift 4, running on iOS 10.3.
I "installed" the library using pod and everything succeeded.

I followed the guide you linked and everything seems working correctly **except** the animation effects. I added the following settings in my controllers (see picture) 
<img width="221" alt="screen shot 2017-07-21 at 15 45 33" src="https://user-images.githubusercontent.com/1215511/28466151-ae542a0a-6e2b-11e7-8f02-6eb6e563d69d.png">

**No animation** are run. Dragging left/right with that settings I should expect a parallax effect, shouldn't I?

Is the issue related to beta version of Xcode or swift 4?

**Comment by ariok** [comment]
Sorry for the late reply I've checked it with Xcode 9 and I cannot reproduce the issue you are reporting. Are you still experiencing it?
