### ISSUE TITLE
Others effects 

### ISSUE THREAD

**Issue by dromerobarria** [ariok/BWWalkthrough#11]
First at all, thanks for this amazing on boarding views, keep the nice work.

It is posible to stop the scroll or slider pass the views , I want to disable the slider for the left in the first view and the right on the last view (cause the images on those view looks bad in contrast of the color in background). Im was searching but with not luck by now.

And if its posible to add animation to each element of those views, like one for the image or title , like a fade animation. I know how to do the animation but I cant find where to implement it. Im new on swift and Im kind of confuse with the controller for all the views.

Thanks in advance.

**Comment by ariok** [comment]
To avoid left and right off-screens you should set Scrollview `bounces` to `false`. 

For the fade animation I suggest to use the `walkthroughDidScroll` method and perform there your custom animations. Something like: 

``` 
func walkthroughDidScroll(position: CGFloat, offset: CGFloat) {
    titleLabel?.alpha = (1.0 - offset) 
}
```
