### ISSUE TITLE
Make my own animations problem

### ISSUE THREAD

**Issue by alexgofman** [ariok/BWWalkthrough#115]
Hi,

I am trying to make my own animation when BWWalkthroughPageViewController launches 

Basically I put my code into viewDidLoad

UIView.animate(withDuration: 5, animations: {
			self.screen_2_rocketImg.frame = CGRect(x: 0, y: 127, width: 375, height: 337)
		}) { (finished) in
			self.screen_2_astronautBgImg.isHidden = false
			self.screen_2_astronautBgImg.frame.size.width += 20
			self.screen_2_astronautBgImg.frame.size.height += 20
		}

and it always just gives error **Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value** on line where **self.screen_2_rocketImg.frame = CGRect(x: 0, y: 127, width: 375, height: 337)**

even though I connected IBOutlets...

Please help
@ariok

**Comment by ariok** [comment]
Sorry for the very late reply. I think you are releasing the view controller (or the object that is handling the animation that you are referring to withing the closure with `self`) before the closure is executed...

**Comment by ariok** [comment]
I'm closing this since my previous answer seems have resolved it.
