### ISSUE TITLE
Deployment target changed to iOS 10.0

### ISSUE THREAD

**Issue by Tripwire999** [ariok/BWWalkthrough#120]
Hi,

I noticed the deployment target was changed to iOS 10.0. Is there a reason for this? I'm still targeting iOS 9.0 so now I can't use your lib anymore.

Thx!

**Comment by ariok** [comment]
Please consider this as bug! I'll try to push a quick fix next week.

**Comment by jjnino** [comment]
any update on this?

**Comment by jjnino** [comment]
Thanks so much!
