### ISSUE TITLE
Is there a way to hide pageControl in specific page?

### ISSUE THREAD

**Issue by imjn** [ariok/BWWalkthrough#125]
I want to hide the `pageControl` in 4th page.
So I did like this
```
    func walkthroughPageDidChange(_ pageNumber: Int) {
        if pageNumber == 3 {
            DispatchQueue.main.async {
                self.pageControl?.isHidden = true
            }
        } else {
            DispatchQueue.main.async {
                self.pageControl?.isHidden = false
            }
        }
    }
```
`self.pageControl?.isHidden = true` is called but `self.pageControl` is always nil and not being hidden.

How can I hide the `pageControl` ?

Thank you in advance :)

**Comment by ariok** [comment]
The issue seems to be related to your implementation, not to BWWalkthrough... you should be sure that pageControl is initialized by your code somehow,

**Comment by ariok** [comment]
No answers after 5 months. I'm closing the issue.
