### ISSUE TITLE
How to make auto redirect(slide) user to previous page inside custompageviewcontroller ?

### ISSUE THREAD

**Issue by mohamadakmalshukri** [ariok/BWWalkthrough#128]
I have two custom page of viewcontroller like "CustomPageViewController" in this project. 

Lets say, CustomPageViewControllerA and CustomPageViewControllerB. While user slide forward to CustomPageViewControllerB but they not finish fill the form inside CustomPageViewControllerA yet then i want make it will auto redirect them to previous page (CustomPageViewControllerA) ?

**Comment by ariok** [comment]
You could implement the logic on your code to check on `walkthroughPageDidChange` if your requirements for that page are fulfilled, or you could block the scrollview until the user filled the form ( `scrollview ` is a public property of `BWWalkthroughViewController`).
