### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by ChrisPearce** [ariok/BWWalkthrough#129]
It would be very helpful if Swift Package Manager was supported by including a Package.swift file.

**Comment by ariok** [comment]
I'm doing a complete porting of BWWalkthrough to SwiftUI. There I will add SPM support but I'm not planning to add other features to this version of the library.

**Comment by rshev** [comment]
Hey! It seems `4.0.1` tag which supposed to include SPM support is not there (maybe not pushed). Any chance you'd push it please?

**Comment by ariok** [comment]
Fixed with 0a35c322c01bc7aafef28bbc362800057f940ead
