### ISSUE TITLE
Problem with 'override init()' function 

### ISSUE THREAD

**Issue by simonarcher** [ariok/BWWalkthrough#13]
Hi there,

On Xcode 6.3 there seems to be a bunch of issues, most of which are fixable with the self-help fixit suggestions, but the one which isn't so obvious is the following method..
-------------
override init() {
        super.init()
        scrollview = UIScrollView()
        controllers = Array() 
}
-------------

which throws the error -> 'Initializer does not override a designated initializer from its superclass'

Not sure how to effectively resolve. Any suggestions? Thanks!

**Comment by ariok** [comment]
Thanks @simonarcher. I can't check and fix the code until the end of April, I'm really sorry about that. I'm going to fix all the issues and in general I'm going to update BWWalkthrough with better code. It has been written with an "old" version on Swift and it really needs to be updated. 

I let this issue open, so that it can address every issue related  to Swift 1.2.

**Comment by orangecoding** [comment]
Damn it, I'll try to fix this issue as well. I'l get back to this if I've found a quick fix.

**Comment by ariok** [comment]
@orangecoding thanks!

**Comment by antgar** [comment]
I don't know if it's a fix but in our app it's working :
 
    required override init(coder aDecoder: NSCoder) {
        scrollview = UIScrollView()
        scrollview.showsHorizontalScrollIndicator = false
        scrollview.showsVerticalScrollIndicator = false
        scrollview.pagingEnabled = true
        scrollview.bounces = false
        
        // Controllers as empty array
        controllers = Array()
        super.init(coder: aDecoder)
    }

**Comment by orangecoding** [comment]
IO can confirm that it works in this way, but... is this the correct way?

**Comment by antgar** [comment]
I don't know if it's the correct way but it's a quick fix that everybody can use.

**Comment by lfarah** [comment]
Thanks!

**Comment by ariok** [comment]
Fixed with #12
