### ISSUE TITLE
swift5 compatibility?

### ISSUE THREAD

**Issue by Vanessa-06** [ariok/BWWalkthrough#132]
Hello - great design / walkthrough - really great! Trying to download this project and to run in latest Xcode and set it up with swift 5 - but getting a lot of errors at compile time 50+ ; lots of method change etc... is there an upgrade for swift 5 please?
Thank you

**Comment by ariok** [comment]
The project has been moved to swift 5 one year ago https://github.com/ariok/BWWalkthrough/commit/15dec421c583a4f8a3edbb77b2737f79b1c790c7 exactly which kind of issue are you experiencing?

**Comment by Vanessa-06** [comment]
Thank you Ariok. I have re-tried to download now and rebuild and it works like a charm - I am sorry I must have dowloaded an old version by mistake. Thank you again
