### ISSUE TITLE
Wrong View positions after presenting ModalViewController in iOS7

### ISSUE THREAD

**Issue by mschonvogel** [ariok/BWWalkthrough#16]
From one of my slides, I am calling a delegate method to present an UIImagePickerController from the MasterViewController. After hiding it, the views of all slides with _speedVariance_ set, are positioned wrong.

Watch: https://youtu.be/_E6Haw8NNA4

**Comment by ariok** [comment]
@mschonvogel  I'm probably going to drop iOS 7 support :/ in the next versions.

**Comment by ariok** [comment]
Hi @mschonvogel I decided to drop support for iOS 7. I close this bug since it seems to be related to iOS 7 only, just let me know if you encounter it with iOS 8 / 9 too and I'll reopen the issue immediately!
