### ISSUE TITLE
how to programmatically close the walkthrough?

### ISSUE THREAD

**Issue by talvinder** [ariok/BWWalkthrough#18]
I am trying to close the walkthrough programmatically after user logs in. I implemented delegate in my class like so:

````var walkthroughDelegate: BWWalkthroughViewControllerDelegate?````

and called the close button like so:

```` self.walkthroughDelegate?.walkthroughCloseButtonPressed!() ````

But the walkthrough is not closing. There is no error either.

**Comment by ariok** [comment]
In depends on the way you have implement your app structure. The Walkthrough doesn't close automatically when function closebuttonpressed is called, in that function you have to implement the logic to remove the Walkthrough from your hierarchy. Check the example to understand how that function is used.

**Comment by talvinder** [comment]
I ended up using delegates to close the walkthrough. Thanks anyway!

**Comment by AliAyasrah** [comment]
@talvinder 
hello
I am trying to do like what you did 
please can you tell me how ?

**Comment by talvinder** [comment]
I used a delegate-protocol in the end to close the walk through. I can share code snippet if you need

Sent from Outlook




On Wed, Jun 24, 2015 at 7:06 PM -0700, "AliAyasrah" <notifications@github.com> wrote:












@talvinder 

hello

I am trying to do like what you did 

please can you tell me how ?

**Comment by AliAyasrah** [comment]
@talvinder 

please share it 
I am new with swift and xCode 

thank you very much

**Comment by AliAyasrah** [comment]
I am trying by protocol - delegate 
but the delegate always return nil

**Comment by channola** [comment]
@talvinder

Do you mind sharing a snippet of the code you used?
