### ISSUE TITLE
go to another view 

### ISSUE THREAD

**Issue by AliAyasrah** [ariok/BWWalkthrough#20]
Hello 

I am trying to go to " another view control in main storyboard " by a button in one of the subviews  

this what I did : 

```
import UIKit
class GamesViewController: UIViewController {

    @IBAction func goToPlayView(sender: UIButton)

   {        
        let mainStb = UIStoryboard(name: "Main", bundle: nil)
        let play = mainStb.instantiateViewControllerWithIdentifier("Play") as! PlayViewController  
        self.presentViewController(play, animated: true, completion: nil);
    }
}
```

and I got this warring :
`
Presenting view controllers on detached view controllers is discouraged 
`

please help

**Comment by ariok** [comment]
@AliAyasrah is this question related to BWWalkthrough?!
