### ISSUE TITLE
Navigationbar issue

### ISSUE THREAD

**Issue by mkwilfreid** [ariok/BWWalkthrough#23]
When embedding the Master View Controller into a navigation bar, and change the way it's a presented to be a push, the scrollview becomes unstable, it's scrolling all over different undefined spaces

**Comment by patonz** [comment]
i had the same problem, and i solved it with the property of scrolling. See my post on StackOverFlow
http://stackoverflow.com/questions/30258686/use-bwwalkthrough-library-without-storyboard-walkthrough-custom

**Comment by mkwilfreid** [comment]
ok thanks. great will give it a try later today, because I’ve decided instead of embedding my controller inside the navigation controller, I just added a bar element.

thanks for the tips.
