### ISSUE TITLE
Update for Swift 2 Please!

### ISSUE THREAD

**Issue by Luccifer** [ariok/BWWalkthrough#25]
``` 
@IBInspectable var staticTags:String {  
        set(value){
            self.notAnimatableViews = value.characters.split{$0 == ","}.map { String($0) }.map{Int(String($0))!}
        }
        get{
            return ",".join(notAnimatableViews.map{String($0)})
        }
    }
```
Error: 'join' has been explicitly marked unavailable here
Error: 'join' is unavailable: call the 'joinWithSeparator()' method on the sequence of elements

**Comment by Luccifer** [comment]
Solution: 
return (notAnimatableViews.map{String($0)}).joinWithSeparator(",")

**Comment by ariok** [comment]
I'm working at an update for Swift 2... I'm sorry it is taking so long, I'll be really busy until the end of September :(
