### ISSUE TITLE
delegate methods not working , Newbie question? 

### ISSUE THREAD

**Issue by jasan-s** [ariok/BWWalkthrough#26]
I'm trying to animate a object(uibutton) to animate when a certain  BWWalkthroughPageViewController(changing pages) view controller appears on screen . using I used delegate method : func walkthroughPageDidChange(pageNumber:Int),  however nothing is happening.   I was told to set the delegate to self in view did load method but not sure how to do that. Any suggestions?

**Comment by ariok** [comment]
Hi this is not a question strictly related to the component, anyway... the `walkthroughPageDidChange` method gets called when the page has been presented. You can setup a delegate and implement in this delegate that function where you implement all the animations that you want to take place when a new page is presented. I suggest to keep track of the current page to avoid performing animation if the same page is presented.
