### ISSUE TITLE
Lock scrolling

### ISSUE THREAD

**Issue by ecstaticax** [ariok/BWWalkthrough#30]
Is there any way to lock scrolling and enable only the use of buttons to go to the different views?

**Comment by ecstaticax** [comment]
Ok, I solved with a simple:

 scrollview.scrollEnabled = false

BTW, how can I enable or disable scrolling in particular views?

Thanks for the work. This class is wonderful.

**Comment by ariok** [comment]
You make it right :) this is the easiest way to lock the scroll. If you want to lock it only for some view (IMO it's a strange behaviour), you can just verify the current page and enable or disable the scroll.

**Comment by ecstaticax** [comment]
It's not a strange Behaviour and I can explain it: the first pages are used to show the main app features, then I need to set some data and I don't want that users can skip pages, so I show the next button only when users input that data. 
Thanks for reply.

**Comment by ariok** [comment]
@ecstaticax Got it, makes absolutely sense :+1:  Even if I've already seen a lot of Apps using it for a variety of different tasks I'm still thinking about BWWalkthrough as a simple...walkthrough. Thanks for sharing your experience!

**Comment by ecstaticax** [comment]
BTW I wasn't able to find a way to check the page number :-/

**Comment by ariok** [comment]
check the `currentPage` property.

**Comment by ecstaticax** [comment]
This is my actual extract from **BWWalkthroughViewController**


```
 override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated);
        
        pageControl?.numberOfPages = controllers.count
        pageControl?.currentPage = 0
        scrollview.scrollEnabled = false

    }
```

I realized that it is loaded only the first time and not everytime. So how can check, when a view is loaded, its **currentPage** property and set **scrollview.scrollEnabled** true or false?
Thanks for support.

**Comment by ariok** [comment]
The `currentPage` is a property that gives you information about the current page shown by the walkthrough and it is **read only**. 

```    
var currentPage:Int{    // The index of the current page (readonly)
        get{
            let page = Int((scrollview.contentOffset.x / view.bounds.size.width))
            return page
        }
    }
```

If you want to disable the scroll for a given page why don't you use delegate function `walkthroughPageDidChange(page:Int)` ?

**Comment by ecstaticax** [comment]
Thanks! I solved it!

 private func updateUI(){
        
        // Get the current page
        
        pageControl?.currentPage = currentPage
        
        // Notify delegate about the new page
        
        delegate?.walkthroughPageDidChange?(currentPage)
        
        if (currentPage < 3)
        {
            scrollview.scrollEnabled = true
        }
        
        else
        {
            scrollview.scrollEnabled = false
        }
        
        
        // Hide/Show navigation buttons
        
        if currentPage == controllers.count - 1{
            nextButton?.hidden = true
        }else{
            nextButton?.hidden = false
        }
        
        if currentPage == 0{
            prevButton?.hidden = true
        }else{
            prevButton?.hidden = false
        }
    }
