### ISSUE TITLE
Rotation support

### ISSUE THREAD

**Issue by SPopenko** [ariok/BWWalkthrough#32]
Control layout is broken after rotation if enable landscape mode. Any suggestions how to fix?

**Comment by ariok** [comment]
BWWalkthrough doesn't support orientation change :/

**Comment by turnoffthelights** [comment]
Hi SPopenko,

We use this code in the "BWWalkthroughViewController.swift" file, to stay in portrait mode:


    override func shouldAutorotate() -> Bool {
        return true
    }
    
    override func supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
        return [UIInterfaceOrientationMask.Portrait,UIInterfaceOrientationMask.PortraitUpsideDown]
    }

**Comment by SPopenko** [comment]
@turnoffthelights thanks for suggestion.
