### ISSUE TITLE
addViewController flow issue

### ISSUE THREAD

**Issue by SPopenko** [ariok/BWWalkthrough#33]
addViewController operate only with controllers view. 
Should it also use addChildViewController and didMoveToParentViewController to correctly host controllers as child?

**Comment by ariok** [comment]
Thanks! It is an interesting feature. I keep track of it and I tag the issue as `enhancement`.

**Comment by ariok** [comment]
Just to letting you know that I'm implementing the new version of BWWalkthrough using a standard View Controller hierarchy ;)

**Comment by ariok** [comment]
I decided not to change the structure that I've implemented to include subviews. I close the issue since I'm not going to complete the regular view controller hierarchy implementation... at least for the  coming releases.
