### ISSUE TITLE
How to make this Walkthrough show all the time?

### ISSUE THREAD

**Issue by jramgit** [ariok/BWWalkthrough#36]
How can I make this to show all time regardless if the user opened the app previously or not?

Thank you

**Comment by ariok** [comment]
It depends on your application structure. Anyway, BWWalkthrough instance doesn't disappear automagically... you have to programmatically implement this behaviour. So if you don't want it to disappear, you are already all set.

**Comment by jramgit** [comment]
Can you explain further? As of now, if I open the app the first time BWWalkthrough instance will show, however, after I close the app and open it again, BWWalkthrough won't show again.

**Comment by ariok** [comment]
Again, this is not part of BWWalkthrough behaviour. Probably you have taken some code from other resources and you are using it together with BWWalkthrough. Is this case possible? BWWalkthrough is just a "container" with navigation logics.

**Comment by ariok** [comment]
Maybe... are you talking about the example project?! in that case I've implemented this behaviour in the `viewController.swift` but please note that this is not the BWWalkthrough behaviour... this is something that I've implemented in the example project... Here the code that define if the walkthrough should be shown or not.  

```
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        let userDefaults = NSUserDefaults.standardUserDefaults()
        
        if !userDefaults.boolForKey("walkthroughPresented") {
            
            showWalkthrough()
            
            userDefaults.setBool(true, forKey: "walkthroughPresented")
            userDefaults.synchronize()
        }
    }
```
