### ISSUE TITLE
Bug? Can't close the presentViewController

### ISSUE THREAD

**Issue by turnoffthelights** [ariok/BWWalkthrough#39]
Hi there,

We want an extra button in the end of the 'Walkthrough' slide. But the code doesn't work when we link it to this new button "Get started Now". (and it use this viewcontroller use the same "BWWalkthroughViewController.swift" file)
 @IBAction func btngetstartednow(sender: AnyObject) {
delegate?.walkthroughCloseButtonPressed?()
}

Thanks,

**Comment by ariok** [comment]
The delegate is not meant to be used in that way. 
You are manually calling a delegate function that should be only called by the class when the "close" button is pressed.

**Comment by turnoffthelights** [comment]
How create then on the end of the slide a big button with the text "Get Started Now" that close this guide?
