### ISSUE TITLE
Last page sometimes doesn't bounce back to its position

### ISSUE THREAD

**Issue by robcornerstone** [ariok/BWWalkthrough#4]
In the example app, I can swipe to the last page that says "Choose the style of every single page...".  If I continue to swipe past the last page, it will briefly expose a blue background and then the page moves back to its offset of scrollview.contentOffset.x == 960.0.  Occasionally though, the last page does not return to the 960 offset, but instead settles on 968.0 (revealing a thin blue stripe along the right edge).

**Comment by ariok** [comment]
@nn1900  This is the problem :) thank you. I'm going to fix it by the end of the week.
