### ISSUE TITLE
Moving views

### ISSUE THREAD

**Issue by justinmakaila** [ariok/BWWalkthrough#43]
For whatever reason, the scroll view is allowing my pages to move in any direction. I've tried setting `alwaysBounceVertical` to `false`, and I've tried to remove all bounce from the `scrollview` to no avail.

Any ideas?

**EDIT** FWIW, my master is presented within a navigation controller. Although the navigation bar should show up, it's not. It seems like the tolerance for the "bounce" is about the same height as a navigation bar.

**Comment by ariok** [comment]
I've never experienced anything similar but it doesn't seems to be something related to the BWWalkthrough implementation... it might be strongly related with your structure. Can you provide more information? maybe a demo project?

**Comment by justinmakaila** [comment]
Yes, I'll put something together

**Comment by justinmakaila** [comment]
@ariok:

I have a `RootViewController`, which is the `rootViewController` of a `UINavigationController` which is my Storyboard Entry Point. The `RootViewController` is configured in a Storyboard, and displays the navigation bar of it's `navigationController`.

Here's the class (edited to only show relevant code):
```
class RootViewController: BWWalkthroughViewController {
    var viewModel: RootViewModel!
    
    @IBOutlet
    private var signUpButton: RoundedRectangleButton!
    
    @IBOutlet
    private var signInButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        scrollview.bounces = false
    }
}

private extension RootViewController {
    func setup() {
        setupWalkthrough()
    }
    
    func setupWalkthrough() {
        guard let pageOne = R.storyboard.onboarding.walkthroughRoot(),
            let pageTwo = R.storyboard.onboarding.walkthroughPage(),
            let pageThree = R.storyboard.onboarding.walkthroughPage(),
            let pageFour = R.storyboard.onboarding.walkthroughPage(),
            let pageFive = R.storyboard.onboarding.walkthroughPage()
        else {
            fatalError("Could not load walkthrough pages!")
        }
        
        addViewController(pageOne)
        addViewController(pageTwo)
        addViewController(pageThree)
        addViewController(pageFour)
        addViewController(pageFive)
    }
}

```

`signUpButton` and `signInButton` float over the walkthrough.

**Comment by justinmakaila** [comment]
<img width="487" alt="screen shot 2016-02-25 at 10 22 37" src="https://cloud.githubusercontent.com/assets/1638996/13323955/bb93a09e-dba9-11e5-8f70-e37563aa9d9b.png">

^ I set the background view color of `pageOne` to black. It appears as if it's not laying out properly within navigation view controllers

**Comment by justinmakaila** [comment]
<img width="487" alt="screen shot 2016-02-25 at 10 23 39" src="https://cloud.githubusercontent.com/assets/1638996/13324001/e55fe608-dba9-11e5-8cdf-926f56c7ca67.png">

^ Here's the same screen after the shift takes place

**Comment by justinmakaila** [comment]
Turns out the issue is not with the library. I missed the `automaticallyAdjustsScrollViewInsets` check box in the storyboard.

**Comment by ariok** [comment]
Thanks for verifying and closing the issue.
