### ISSUE TITLE
Problems with orientation and modally presented views

### ISSUE THREAD

**Issue by fishfisher** [ariok/BWWalkthrough#46]
First of all, thanks for your great work!
I have an issue when it comes to displaying BWWalkthroughViewController on the iPad. When in landscape the constraints are all wrong and I have not found a solution for it. It is also displayed wrong if the BWWalkthroughViewController is presented as PageSheet or FormSheet. Any ideas?
Regards, Erik

**Comment by ariok** [comment]
Landscape orientation is not yet supported. I add this as a bug, I try to fix constraints generation to be dynamically handled.

**Comment by knly** [comment]
I just submitted a pull request to support landscape orientations, it may be relevant to this issue: #60

**Comment by ariok** [comment]
thanks! going to merge very soon!

**Comment by apiejh** [comment]
I've submitted a pull request that (if accepted) should help you: [#80](https://github.com/ariok/BWWalkthrough/issues/46)

**Comment by ariok** [comment]
#80 has been merged.
