### ISSUE TITLE
Only show close button on last page

### ISSUE THREAD

**Issue by marcoscurvello** [ariok/BWWalkthrough#47]
Not an issue really, just a desired scenario. Can I only show the close button on the last walkthrough page? Thanks so much for awesome repo!

**Comment by ariok** [comment]
Sure, you can link the `closeButton` property to your viewController, then, you need to setup a `BWWalkthroughViewControllerDelegate` and you can use its `walkthroughPageDidChange(pageNumber:)` function to hide the `closeButton` if the received page is the last one (just doing something like `pageNumber == walkthrough.numberOfPages -1`).
