### ISSUE TITLE
How to set the view's tags that I want to exclude the automatic animations

### ISSUE THREAD

**Issue by lazyeo** [ariok/BWWalkthrough#49]
I'm a very beginner :(
This project is great ! 
I can attach the pages to the master with  automatic animations
But I don't know how to exclude some views from the animation
What' the `staticTags` ? Should I create a runtime arguments with the key-path of `staticTags`?
And how to set the tags to the views I don't need animations?

THX :)

**Comment by ariok** [comment]
From Interface Builder, in the attribute inspector for a specific BWWalkthrough-Page, you can list the tags for the views that you don't want to animate. Check this tutorial for more info http://www.thinkandbuild.it/creating-custom-walkthroughs-for-your-apps/
