### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [ariok/BWWalkthrough#53]
How can I use this library in Objective-C project, although this library is written in Swift?

**Comment by ariok** [comment]
Sure! You can use `BWWalkthrough` classes in your Objective-C projects. You have only to include the "yourproject-swift.h" header when you want to use a swift class. Check the [documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) for more info.

Here is a quick example written in objective-c:
``` objective-c

- (IBAction)showWalkthrough:(id)sender{
    UIStoryboard *st = [UIStoryboard storyboardWithName:@"Main" bundle:nil];

    BWWalkthroughViewController * walkthrough = [st instantiateViewControllerWithIdentifier:@"walkthrough"];
    UIViewController *pageOne = [st instantiateViewControllerWithIdentifier:@"page_one"];
    UIViewController *pageTwo = [st instantiateViewControllerWithIdentifier:@"page_two"];
    
    [walkthrough addViewController:pageOne];
    [walkthrough addViewController:pageTwo];
    
    [self presentViewController:walkthrough animated:true completion:nil];
}
```
