### ISSUE TITLE
The landscape there is something wrong with the logic

### ISSUE THREAD

**Issue by danwey** [ariok/BWWalkthrough#55]
![error](https://cloud.githubusercontent.com/assets/6631373/15424230/185dd842-1eb4-11e6-9135-f5ab2a52edd8.png)

please add landscape model.

**Comment by ariok** [comment]
Landscape is not currently supported. I'm working at version 2.0 that will be based on size classes and will support landscape and portrait.

**Comment by knly** [comment]
Hi @ariok, can you suggest a way to disable landscape orientation for the walkthrough?
