### ISSUE TITLE
preferredStatusBarStyle not triggered

### ISSUE THREAD

**Issue by albertml** [ariok/BWWalkthrough#57]
I need to change the status bar color. I set View controller-based status bar appearance to YES cause I need to hide status bar on specific viewcontroller. Overriding preferredStatusBarStyle on class extending your library will not triggered.

**Comment by ariok** [comment]
I don't think this issue related to BWWalkthrough code. preferredStatusBarStyle defines the color of the status bar text, not its visibility.

**Comment by ariok** [comment]
anyway, this issue might be strongly related with the structure you have implemented. You can try calling something like directly from a  BWWalkthrough page: `[[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent];` it should work.
