### ISSUE TITLE
Infinite scrolling not supported

### ISSUE THREAD

**Issue by jhrasco** [ariok/BWWalkthrough#59]
Is there a way to make it scroll infinitely? Like when the user reaches the last page, the walkthrough will go back to first page on the next swipe.

**Comment by ariok** [comment]
@jhrasco this is not a planned behaviour for BWWalkthrough. Anyway, you could extend `BWWalkthroughViewController` in that way: when the last view controller is presented and the next button is pressed you just call `gotoPage(0)`. Obviously it doesn't handle the case where a user is manually scrolling through view controllers.
