### ISSUE TITLE
Problem After Walkthrough

### ISSUE THREAD

**Issue by channola** [ariok/BWWalkthrough#62]
Hello, I have a problem with leaving the walkthrough to get to my login page. How do you connect to login view controller out of walkthrough? Any help please.

**Comment by ariok** [comment]
This issue I strictly related to your App implementation, did you tried to switch the root controller? or you can just keep the walk through in the hierarchy and present your other view controllers above it (I don't like this method though). Another way is using view containment... create a container and switch contents as you need.

**Comment by channola** [comment]
Thank you so much!
