### ISSUE TITLE
error swift 3

### ISSUE THREAD

**Issue by travjzx** [ariok/BWWalkthrough#63]
I am receiving this error in swift 3

 for(i in 0 ..< subsWeights.count ){

expected ',' separator

this is  in BWWalkthroughPageViewController.swift

**Comment by kvnbautista** [comment]
@travjzx Try this
for i in 0 ..< subsWeights.count

**Comment by ariok** [comment]
I still have to port code to Swift 3. I tag the issue as enhancement

**Comment by antonioreyna** [comment]
Hi, thanks for this awesome library, when do you think can release swift 3 version? :D

**Comment by NemOry** [comment]
I hope the swift 3 version is going to be released soon. can't wait :) thanks a lot for this great lib

**Comment by hainguyen86** [comment]
xcode 8 is out, it's time to upgrade :D

**Comment by iTh3End** [comment]
please update lib to swift 3

**Comment by ariok** [comment]
Guys, I'm in Honeymoon right now, I'll be back in a week and I'll release :)

**Comment by hilalbaig** [comment]
Please make it as soon as possible. 
Thanks for the great library.

**Comment by LiborZ** [comment]
Yes please, upgrade this as soon as you get home. Thanks :)

**Comment by francoisduchemin** [comment]
Yep upgrade would be great!

**Comment by willeeklund** [comment]
For those os you who want a working Swift 3 version: you can use the version in PR #72. @francoisduchemin @LiborZ @hilalbaig @iTh3End @NemOry @antonioreyna

**Comment by francoisduchemin** [comment]
Thanks @willeeklund PR #72 is working great!

**Comment by ariok** [comment]
I've quickly checked PR #72, I cannot fully check it since I'm still OOO without my laptop (honeymoon... she is in charge, you know 😅) I will merge and update pod stuff in a few days, in the meanwhile please consider using PR #72.
