### ISSUE TITLE
launch navigation controller from a page

### ISSUE THREAD

**Issue by brokeniceinteractive** [ariok/BWWalkthrough#66]
I have a strange problem, i added a button in a page of slider, with this action:

```
let blckView = stb.instantiateViewControllerWithIdentifier("blc") as! BlockedContactTableViewController
        blckView.navigationItem.leftBarButtonItem = UIBarButtonItem(title: "Back", style: UIBarButtonItemStyle.Plain, target: self, action: "goBack")
        let navController = UINavigationController(rootViewController: blckView) // Creating a navigation controller with resultController at the root of the navigation stack.
        self.presentViewController(navController, animated: true, completion: nil)
```

The navigation has been displayed, but the page BWWalkthroughPageViewController has been resized wrong, and when i close the new navigation i'm not able to scroll but i can only click close button, any idea?

**Comment by ariok** [comment]
How can I understand which issue are you experiencing checking the code you provided? Looking at the issue from this point of view I cannot understand if it is related to BWWalkthrough.
