### ISSUE TITLE
Constraint issue in Xcode 8 Beta 6

### ISSUE THREAD

**Issue by xoniq** [ariok/BWWalkthrough#67]
`.../Pods/BWWalkthrough/Pod/Classes/BWWalkthroughViewController.swift:236:53: Cannot assign value of type '[NSLayoutConstraint]' to type 'NSArray?'`

// EDIT //

Fixed by changing
```private var lastViewConstraint:NSArray?```
To:
```private var lastViewConstraint:[NSLayoutConstraint]?```

**Comment by ariok** [comment]
@xoniq thanks. Xcode 8 and Swift 3 are not yet supported. Working on a new branch that I'm going to upload soon.
