### ISSUE TITLE
NSLayoutContraint crash in BWWalkthroughViewController

### ISSUE THREAD

**Issue by cqin5** [ariok/BWWalkthrough#73]
Xcode 8 with Swift 3.0

On line 229, 
`scrollview.addConstraints(NSLayoutConstraint.constraintsWithVisualFormat("H:[previousView]-0-[view]", options:[], metrics: nil, views: ["previousView":previousView,"view":vc.view]))`

throws

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue nsli_superitem]: unrecognized selector sent to instance 0x60000024d7a0

I apologize that I'm not too familiar with creating constraints in code, therefore can't offer anything more than pointing it out.

**Comment by olegnaumenko** [comment]
Same happens for me in simulator

**Comment by cqin5** [comment]
@olegnaumenko take a look at this https://github.com/ariok/BWWalkthrough/pull/72 , it solved my problem.

**Comment by willeeklund** [comment]
Yes I also noticed this problem. It is solved in the referred pull request (#72).

**Comment by olegnaumenko** [comment]
Thank You, solved for me too.

**Comment by ariok** [comment]
Please use PR #72 I'll merge it a few days. I'm currently OOO.

**Comment by gabrieloliva** [comment]
I had the same problem and the PR #72 fixed it.
