### ISSUE TITLE
Need Swift 2.3 version of this library

### ISSUE THREAD

**Issue by preetirani** [ariok/BWWalkthrough#75]
I need to integrate this library in my project which is using swift 2.3 , through pods . Please let me know to get that version of this library

**Comment by 27deabril** [comment]
My project is also using Swift 2.3 and I've just successfully integrated with this class through pods. Are you using that famous "mini-script" to configure your pods?:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "2.3"
        end
    end
end
```

In case you are not, just add that to the end of your podfile, run a new pod install and it should work.

**Comment by ariok** [comment]
I close the issue since we already moved the project to Swift 3.0. Please try what @27deabril suggested. Anyway you can easily download release 1.1.1 and update it to swift 2.3 :)
