### ISSUE TITLE
Is it possible to hide the pageControl while in transition?

### ISSUE THREAD

**Issue by alexandrutelegredean** [ariok/BWWalkthrough#76]
Is it possible to hide the pageControl when the screen is in transition ( from let's say page 3 to 4 where 4 is the last ) not when the transition is completed ?

**Comment by ariok** [comment]
You have to subclass and implement that as a custom behaviour. Currently the library checks for page controls to hide/show at the end of the transition. (it might be a nice feature for the next release though... thanks for pointing it out).
