### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by albertml** [ariok/BWWalkthrough#77]
Cocoapods of this library not updated to Swift 3

**Comment by terflogag** [comment]
Check this issue : https://github.com/ariok/BWWalkthrough/issues/63

**Comment by ariok** [comment]
@albertml I'm working on the pod update now.

**Comment by ariok** [comment]
I'm encountering a lot of issues. CocoaPods is currently not compatible with Xcode 8. I've installed the rc2... let's try that way. Every time I need to update this repo for CocoaPods is a pain...

**Comment by ariok** [comment]
I'm still getting error while trying to push the pod to trunk. Currently I'm getting "The `master` repo is not a git repo.". I cannot complete and close this issue... I put it on hold.

**Comment by haydarKarkin** [comment]
Hi @ariok ,

Is there any progress about swift 3? Please let us know how it goes.

Thanks

**Comment by ariok** [comment]
BWWalkthrough has been updated to fully support Swift 3 with CocoaPods.
