### ISSUE TITLE
Start BWWalkthrough from viewDidLoad()

### ISSUE THREAD

**Issue by DK-Webentwicklung** [ariok/BWWalkthrough#79]
Hi, i have a problem with your Class.

If i start the flow with an uibutton it works perfectly but i want to start the flow without a button. How can i do this?

I test to copy the buttoncode into the viewDidLoad() without success.

This is my code:

`
        let stb = UIStoryboard(name: "Main", bundle: nil)
        let walkthrough = stb.instantiateViewController(withIdentifier: "walkthroughcontainer") as! BWWalkthroughViewController
        let page_one = stb.instantiateViewController(withIdentifier: "page_1") as UIViewController
        let page_two = stb.instantiateViewController(withIdentifier: "page_2") as UIViewController
        let page_three = stb.instantiateViewController(withIdentifier: "page_3") as UIViewController
        let page_four = stb.instantiateViewController(withIdentifier: "page_4") as UIViewController
        let page_five = stb.instantiateViewController(withIdentifier: "page_5") as UIViewController
        let page_six = stb.instantiateViewController(withIdentifier: "page_6") as UIViewController
        let page_seven = stb.instantiateViewController(withIdentifier: "page_7") as UIViewController
        let page_eight = stb.instantiateViewController(withIdentifier: "page_8") as UIViewController
        
        // Attach the pages to the master
        walkthrough.delegate = self
        walkthrough.addViewController(page_one)
        walkthrough.addViewController(page_two)
        walkthrough.addViewController(page_three)
        walkthrough.addViewController(page_four)
        walkthrough.addViewController(page_five)
        walkthrough.addViewController(page_six)
        walkthrough.addViewController(page_seven)
        walkthrough.addViewController(page_eight)
        
        self.present(walkthrough, animated: true, completion: nil)`

Thanks for support!

**Comment by ariok** [comment]
You are trying to present a view controller in the viewDidLoad... this is the problem. You could show directly the walkthrough instead of presenting it through another view controller or, if you really need to pass through another view controller use at least the viewDidAppear method.
