### ISSUE TITLE
Changing from split view to full view forces walkthrough to the initial page

### ISSUE THREAD

**Issue by kschins** [ariok/BWWalkthrough#87]
If the user is viewing the walkthrough on an iPad in split view (multi-tasking mode), and they make the application full screen the user is immediately taken back to the first page as opposed to still viewing the same page they were on when viewing the walkthrough in split view.

**Comment by ariok** [comment]
I think this behaviour has been introduced with this commit ade308d6e64c178dd0e351629cbecaab1cdce50d. What do you think @apiejh?

**Comment by apiejh** [comment]
With this commit, I'm adjusting the offset of the scrollview to the beginning of the current page whenever the viewport size changes. In principle, this should not take you to a different page. @kschins could you please give more info on how to reproduce this issue? Are you in landscape or portrait mode? Which iPad is it? Is it possible for you to record a screencast? I've tried reproducing this issue in the example app shipping with the library but everything worked fine for me.

**Comment by ariok** [comment]
Still no replies after 3 months. I close the issue feel free to open it again when you will be able to provide more info.
