### ISSUE TITLE
Drag All Over The Screen Not Only Left Or Right Side

### ISSUE THREAD

**Issue by MuhammadAhmedBaig** [ariok/BWWalkthrough#89]
Hey!,
I Face Issue, I Integrate Walkthrough But The pages not only move left or right but also moves from upside or down side in short i can move all the Image to all over the screen,
Please See the Screen shot:
![simulator screen shot 13-feb-2017 7 04 06 pm](https://cloud.githubusercontent.com/assets/11391728/22886458/cbc2d664-f21f-11e6-8718-1967c5a1f1cd.png)

**Comment by ariok** [comment]
Please follow #86
