### ISSUE TITLE
NavigationController doesn't show when the "container view" is embedded in NavigationController

### ISSUE THREAD

**Issue by MaikoHermans** [ariok/BWWalkthrough#91]
I'm currently trying to make a walkthrough by using BWWalkthrough
I've followed the tutorial and example codes to get it working. Now I want to add a `NavigationController` to the `Walkthrough`

I did this by embedding the `BWWalkthroughViewController` into a `Navigation Controller`

The `navigation` bar then shows up in the screen and I've added `barbuttons` to it.

However as soon as I run the code the `navigationbar` is nowhere to be found.

How can I make sure that the navigation bar does show up?

**Comment by ariok** [comment]
Interesting, thanks for sharing. I'll check it in the next days (sorry for the late replies guys but I had a really busy month)

**Comment by MaikoHermans** [comment]
@ariok For now I did fix it by using a navigation bar and setting the `height constraint` to `70px`

Also useful to mention when you want an `imageview` as the background for all the screens so you set it in the `WalkthroughViewController` all the views are being displayed behind it. Meaning you have to create a custom way to set a background image on a `UIView`

not that big of a problem just figured it would be worth mentioning

**Comment by ariok** [comment]
got it @MaikoHermans, I keep the issue open and I'll try to solve the `imageView` issue too.

**Comment by ariok** [comment]
I close the issue since it seems to be a very specific case of your app UI.  You are faking a navigation bar but the navigation implemented by the Walkthrough doesn't need it... your solution seems to work correctly for your needs 👍
