### ISSUE TITLE
Button's Property Next Button in UIStoryBoard

### ISSUE THREAD

**Issue by AbdulAj** [ariok/BWWalkthrough#94]
As u told in your Documentation
"Now that the elements are in place you have to set IBOutlet and IBAction connections:
1) Connect your next button element to the view controller property nextButton (ctrl + click on the button and drag toward the view controller icon)."
i tried a lot but i did't find this property
kindly help

**Comment by AbdulAj** [comment]
As u told in your Documentation
CONTAINER SETUP

"To create a new container you have just to add a new view controller into the Storyboard, from the Identity Inspector set its class to BWWalkthroughViewController and define a Storyboard ID (I’ve used ”container”)."
then, in which file or class, IBOutlets and actions would be written because we have assigned it BWWalkthroughViewController class which is objective C file.
kindly tell me, on this step, i am little bit confused

**Comment by ariok** [comment]
closed with #95
