### ISSUE TITLE
Is it possible to add buttons to BWWalkthroughPageViewController.swift?

### ISSUE THREAD

**Issue by bmemon201** [ariok/BWWalkthrough#96]
Im trying to add a few buttons within the pageViewControllers but I keep running into errors.. #

**Comment by ariok** [comment]
can you provide any useful information about the issue? I really don't know how can I help you otherwise.

**Comment by bmemon201** [comment]
Apologies. I am trying to edit the walkthrough so that the pages in the walkthrough contain their own pages. For example page_1 of the walkthrough would ask for user input into a UITextField. On page_2 there would be a label asking for the biological gender with two buttons present, one for Male and another Female. And so on.. My walkthrough currently contains 5 pages, each with some sort of @IBOutlet

**Comment by ariok** [comment]
which errors are you experiencing?

**Comment by bmemon201** [comment]
Whenever I add @IBOutlet to BWWalkthroughPageViewController.swift and make the connections, the buttons do not appear in the simulator..

**Comment by bmemon201** [comment]
open class BWWalkthroughPageViewController: UIViewController, BWWalkthroughPage {
    
    weak open var delegate:BWWalkthroughViewControllerDelegate?
    
    @IBOutlet open var maleButton:UIButton?
    @IBOutlet open var femaleButton:UIButton?

**Comment by ariok** [comment]
No replies to my message I suppose I can close the issue.
