### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by MojtabaHs** [ariok/BWWalkthrough#98]
When choosing a RTL language in "Localization native development region" the FW behave odd and jumpy! Beside, order of the pages reversed (not excepted) and scroll direction not changes to RTL.

For testing, just set Localization native development region to some RTL language like "ar" or "fa".

**Comment by MojtabaHs** [comment]
Any updated yet ?
2,369 persons are waiting 💪

**Comment by ariok** [comment]
I'm not working on it yet. I received your original message by email before you edited it. As you know, this is open source code, please feel free to edit it  💪🏻 😉 as you wish!

**Comment by MojtabaHs** [comment]
#100 Please take a look 💪

**Comment by ariok** [comment]
@MojtabaHs I tried your code. When I launched the example it wasn't working properly (all the views were at wrong positions). I'll be glad to include your code in the next version! I keep the issue open.

**Comment by MojtabaHs** [comment]
Yes you are right. I forgot to check LTR after fixing RTL. What a shame. But I will fix it as soon as possible. This excelent framework should work for all nations.

**Comment by reenaphilip** [comment]
Is the RTL support done?

**Comment by ariok** [comment]
@reenaphilip no it has not been implemented. The previous pull request wasn't working correctly.

**Comment by dornaCp** [comment]
Is there any update on RTL?
Is there any workaround?

**Comment by ariok** [comment]
I'll not add RTL soon. I'm working at a complete rework of this library with SwiftUI.
