### ISSUE TITLE
add new pages after walkthrough presentation

### ISSUE THREAD

**Issue by devAlikhani** [ariok/BWWalkthrough#99]
Is it possible to male the users able to add pages? Like, in each page, if the user chose any option, then, according to her choice, the next page gets added to the Walkthrough?

**Comment by ariok** [comment]
BWWalkthrough wasn't meant to be used in that way, anyway you could dynamically add a new view controller with 
`func add(viewController:UIViewController)`, the same function that use use to initialize the walkthrough pages. Every times that you call the `add` function all the constraints are updated and you should be able to get the new controller attached at the end of the "pages" list.
